name: CI

on:
    push:
        branches: [develop]
    pull_request:
        branches:
            - '*'

jobs:
    build-test-lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: build app
              run: npm install

            - name: Run tests
              run: npm run test

            - name: Run linter
              run: npm run lint
